### ISSUE TITLE
LibraryMQTT not usable with paho-mqtt 2.0.0

### ISSUE THREAD

**Issue by BriceBoy** [randomsync/robotframework-mqttlibrary#34]
```
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details

Traceback (most recent call last):
  File "C:\WINDOWS\ServiceProfiles\NetworkService\AppData\Roaming\Python\Python37\site-packages\MQTTLibrary\MQTTKeywords.py", line 71, in connect
    self._mqttc = mqtt.Client(client_id, clean_session)
  File "C:\WINDOWS\ServiceProfiles\NetworkService\AppData\Roaming\Python\Python37\site-packages\paho\mqtt\client.py", line 767, in __init__
    "Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details"
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details
```

**Comment by romanliv** [comment]
I tried to address this issue in https://github.com/randomsync/robotframework-mqttlibrary/pull/35, maybe someone with enough permissions can review and merge it if the fix is ok.

**Comment by BriceBoy** [comment]
Thank you ! I hope this will be done ^^

**Comment by tyorkco** [comment]
While waiting for paho 2.0 support is there anyway to get a temporary relief fix that at minimum allows this library to run as 1.0 but in paho 2.0 environment?


All it would take is to add this import to MQTTKeywords.py:
```
import paho.mqtt as paho
```

And replace line 71 of MQTTKeywords.py with:

```
if paho.__version__ < "2.0":
    self.mqtt.Client(client_id, clean_session)
else:
    self.mqtt.Client(mqtt.CallbackAPIVersion.VERSION1, client_id, clean_session)
```
